"""add_otp_and_rate_limit

Revision ID: 43c13e605748
Revises: 202606240002
Create Date: 2026-06-25 12:06:30.662120
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '43c13e605748'
down_revision: Union[str, None] = '202606240002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('window_minute', sa.String(length=20), nullable=False),
    sa.Column('window_day', sa.String(length=10), nullable=False),
    sa.Column('rpm_count', sa.Integer(), nullable=False),
    sa.Column('rpd_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_id'), 'rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limits_user_id'), 'rate_limits', ['user_id'], unique=False)
    op.drop_index('idx_stt_user', table_name='speech_to_text')
    op.drop_index('idx_tts_user', table_name='text_to_speech')
    op.drop_index('ix_users_api_key', table_name='users')
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.create_index('ix_users_api_key', 'users', ['api_key'], unique=False)
    op.create_index('idx_tts_user', 'text_to_speech', ['user_id'], unique=False)
    op.create_index('idx_stt_user', 'speech_to_text', ['user_id'], unique=False)
    op.drop_index(op.f('ix_rate_limits_user_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_id'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
